apiVersion: limit.myafq.com/v1alpha1
kind: ClusterLimit
metadata:
  name: default
spec:
  limitRange:
    limits:
    - default:
        cpu: "700m"
        memory: "900Mi"
      defaultRequest:
        cpu: "110m"
        memory: "111Mi"
      type: Container
