apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: limit-operator
  template:
    metadata:
      labels:
        name: limit-operator
    spec:
      serviceAccountName: limit-operator
      containers:
        - name: limit-operator
          image: quay.io/myafk/limit-operator:0.2
          command:
          - limit-operator
          imagePullPolicy: Always
          resources:
            requests:
              memory: "25Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"

          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "limit-operator"
