apiVersion: limit.myafq.com/v1alpha1
kind: ClusterLimit
metadata:
  name: limited
spec:
  namespaceSelector:
    matchLabels:
      limit: "limited"
  limitRange:
    limits:
    - type: Container
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "10m"
        memory: "10Mi"
      default:
        cpu: "100m"
        memory: "128Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
    - type: Pod
      max:
        cpu: "2"
        memory: "2Gi"
